name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use .NET Core sdk
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'  # You can change this to your desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test --no-build
